ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: 3000

storage:
  driverClassName: "org.postgresql.Driver"
  jdbcUrl: ${?DB_JDBC_URL}
  dbUser: ${?DB_USER}
  dbPassword: ${?DB_PASSWORD}